# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1fae9a660a861d3dc6d10799677648928eeda167c18379d3d7f35f91dc02b5f1bbf2937b52755a2c7da2be620d1b98ca00798928ffa84771eeb7b679667f170

test:
  secret_key_base: 20c92a77f0a56ccd13f36615e78f633ce78f733fbb20bb6c13f8cd48f35b3fecc0282f77a46a3933da6b17d702f94bc73cfef508c4a76c8a3e5a38daa4cb4ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
